### PR TITLE
Update for Satisfactory 1.0

### PR DESCRIPTION
**Pull request by Feuerpfeil**
fix FEX installation and edit docker-compose for new port mapping introduced in 1.0

(my first time making a pull request. hope I'm doing this right...)

### CODE REVIEW

**Comment by sa-shiro** [comment]
I'll have a look at this later this day!

**Comment by sa-shiro** [comment]
It looks good so far! no crash on start, just testing a bunch of stuff to then update the readme!

**Comment by sa-shiro** [comment]
Yeah.... the Conveyor Belt issue persist :(
The server will crash once you are trying to place conveyors

**Comment by calebroelens** [comment]
Hey just wanted to comment that the docker image maybe needs to expose the port 7777 with EXPOSE 7777/udp and EXPOSE 7777/tcp. It did'nt work without this for me.

**Comment by sa-shiro** [comment]
> Hey just wanted to comment that the docker image maybe needs to expose the port 7777 with EXPOSE 7777/udp and EXPOSE 7777/tcp. It did'nt work without this for me.

I checked the PR without modifications and it worked just fine for me tho

**Pull request merged**
